'use strict';
angular.module('main')
  .service('Data', function () {

    console.log('Hello from your Service: Data in module main');
    // TODO: do your service thing
    var vm = this;
    vm.myJobs = [{
      'Client_id': '1',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'hannah.millar@live.co.uk',
      'Client_Mobile': '07951817249',
      'Client_Pickup_Address': '12 Brockwood Close',
      'Client_Pickup_Postcode': 'NE63 8LT',
      'Client_Dropoff_Address': '1 Ashbourne cres',
      'Client_Dropoff_Postcode': 'NE63 8AU',
      'Client_lat': '55.172043',
      'Client_lng': '-1.581547',
      'Client_Pickup_Time': '2015-01-29 16:00:00'
    }, {
      'Client_id': '2',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@testing.com',
      'Client_Mobile': '07951817123',
      'Client_Pickup_Address': '1 ashbourne cres',
      'Client_Pickup_Postcode': 'NE63 8AU',
      'Client_Dropoff_Address': '22 home street ',
      'Client_Dropoff_Postcode': 'NE63 8LT',
      'Client_lat': '55.181091',
      'Client_lng': '-1.573507',
      'Client_Pickup_Time': '2015-01-30 15:40:00'
    }, {
      'Client_id': '3',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'hannah.millar@live.co.uk',
      'Client_Mobile': '07951817249',
      'Client_Pickup_Address': '12 Brockwood Close',
      'Client_Pickup_Postcode': 'NE63 8LT',
      'Client_Dropoff_Address': '1 ashbourne cres',
      'Client_Dropoff_Postcode': 'ne63 8au',
      'Client_lat': '55.172043',
      'Client_lng': '-1.581547',
      'Client_Pickup_Time': '2015-01-31 16:50:00'
    }];
    vm.availableJobs = [{
      'Client_id': '1',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'hannah.millar@live.co.uk',
      'Client_Mobile': '07951817249',
      'Client_Pickup_Address': '12 Brockwood Close',
      'Client_Pickup_Postcode': 'NE63 8LT',
      'Client_Dropoff_Address': '1 Ashbourne cres',
      'Client_Dropoff_Postcode': 'NE63 8AU',
      'Client_lat': '55.172043',
      'Client_lng': '-1.581547',
      'Client_Pickup_Time': '2015-01-29 16:00:00'
    }, {
      'Client_id': '2',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@testing.com',
      'Client_Mobile': '07951817123',
      'Client_Pickup_Address': '1 ashbourne cres',
      'Client_Pickup_Postcode': 'NE63 8AU',
      'Client_Dropoff_Address': '22 home street ',
      'Client_Dropoff_Postcode': 'NE63 8LT',
      'Client_lat': '55.181091',
      'Client_lng': '-1.573507',
      'Client_Pickup_Time': '2015-01-30 15:40:00'
    }, {
      'Client_id': '3',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'hannah.millar@live.co.uk',
      'Client_Mobile': '07951817249',
      'Client_Pickup_Address': '12 Brockwood Close',
      'Client_Pickup_Postcode': 'NE63 8LT',
      'Client_Dropoff_Address': '1 ashbourne cres',
      'Client_Dropoff_Postcode': 'ne63 8au',
      'Client_lat': '55.172043',
      'Client_lng': '-1.581547',
      'Client_Pickup_Time': '2015-01-31 16:50:00'
    }, {
      'Client_id': '4',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Ashbourne Crescent, Ashington, United Kingdom',
      'Client_Pickup_Postcode': 'NE63 8AU',
      'Client_Dropoff_Address': 'Ashbourne Crescent, Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'NE638aU',
      'Client_lat': '55.180931',
      'Client_lng': '-1.573894',
      'Client_Pickup_Time': '2015-02-18 10:36:00'
    }, {
      'Client_id': '5',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Blyth, Northumberland, United Kingdom',
      'Client_Pickup_Postcode': 'NE',
      'Client_Dropoff_Address': 'Ashbourne Crescent, Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'NE63',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-19 11:20:00'
    }, {
      'Client_id': '6',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'NE1, United Kingdom',
      'Client_Dropoff_Address': 'London, United Kingdom',
      'Client_Dropoff_Postcode': 'SW11, United Kingdom',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-16 11:40:00'
    }, {
      'Client_id': '7',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'London, United Kingdom',
      'Client_Pickup_Postcode': 'SW11, United Kingdom',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'NE1, United Kingdom',
      'Client_lat': '51.467594',
      'Client_lng': '-0.170098',
      'Client_Pickup_Time': '2015-02-16 11:40:00'
    }, {
      'Client_id': '8',
      'Client_Name': 'Lewis',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Durham, United Kingdom',
      'Client_Pickup_Postcode': 'DH',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'NE1',
      'Client_lat': '54.523445',
      'Client_lng': '-1.217465',
      'Client_Pickup_Time': '2015-02-17 00:20:00'
    }, {
      'Client_id': '9',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'Hannah@Updated.com',
      'Client_Mobile': '07905824888',
      'Client_Pickup_Address': 'Pink Lane Coffee, Pink Lane, Newcastle upon Tyne',
      'Client_Pickup_Postcode': 'NE1',
      'Client_Dropoff_Address': 'Ponteland, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-16 13:50:00'
    }, {
      'Client_id': '10',
      'Client_Name': 'Lewis Dimmick',
      'Client_Email': 'Lewis@Update.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Sunderland, United Kingdom',
      'Client_Pickup_Postcode': 'Su',
      'Client_Dropoff_Address': 'Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'NE1',
      'Client_lat': '52.187126',
      'Client_lng': '-1.606145',
      'Client_Pickup_Time': '2015-02-16 14:00:00'
    }, {
      'Client_id': '11',
      'Client_Name': 'Lewis Updated',
      'Client_Email': 'Lewis@testing.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Hull, United Kingdom',
      'Client_Pickup_Postcode': 'HU',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '53.709316',
      'Client_lng': '-0.114111',
      'Client_Pickup_Time': '2015-02-16 14:10:00'
    }, {
      'Client_id': '12',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'Hannah@Working.com',
      'Client_Mobile': '07905824888',
      'Client_Pickup_Address': 'Dundee, United Kingdom',
      'Client_Pickup_Postcode': 'DU',
      'Client_Dropoff_Address': 'Pink Lane Coffee, Pink Lane, Newcastle upon Tyne',
      'Client_Dropoff_Postcode': 'ne1',
      'Client_lat': '56.462017',
      'Client_lng': '-2.970721',
      'Client_Pickup_Time': '2015-02-17 17:40:00'
    }, {
      'Client_id': '13',
      'Client_Name': 'Lewis Dimmick',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Dunston, Gateshead, United Kingdom',
      'Client_Pickup_Postcode': 'GH1',
      'Client_Dropoff_Address': 'Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne63',
      'Client_lat': '54.952000',
      'Client_lng': '-1.639000',
      'Client_Pickup_Time': '2015-02-28 11:30:00'
    }, {
      'Client_id': '14',
      'Client_Name': 'Dave Davidson',
      'Client_Email': 'Davie@test.com',
      'Client_Mobile': '1231231231',
      'Client_Pickup_Address': 'Edinburgh, United Kingdom',
      'Client_Pickup_Postcode': 'EH1',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '55.957394',
      'Client_lng': '-3.187262',
      'Client_Pickup_Time': '2015-02-17 01:00:00'
    }, {
      'Client_id': '15',
      'Client_Name': 'Ben Fairlie',
      'Client_Email': 'Ben@ben.com',
      'Client_Mobile': '07905824811',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'Ne1',
      'Client_Dropoff_Address': 'Durham, United Kingdom',
      'Client_Dropoff_Postcode': 'DH1',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-17 12:20:00'
    }, {
      'Client_id': '16',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'Hannah@Fictional.com',
      'Client_Mobile': '07905824888',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'Ne1',
      'Client_Dropoff_Address': 'Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'NE63',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-17 11:50:00'
    }, {
      'Client_id': '17',
      'Client_Name': 'Lewis Dimmick',
      'Client_Email': 'Lewis@eXAMPLE.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Ashington, United Kingdom',
      'Client_Pickup_Postcode': 'NE63',
      'Client_Dropoff_Address': 'Durham, United Kingdom',
      'Client_Dropoff_Postcode': 'DH1',
      'Client_lat': '55.182777',
      'Client_lng': '-1.563878',
      'Client_Pickup_Time': '2015-02-17 12:00:00'
    }, {
      'Client_id': '18',
      'Client_Name': 'davie@dave.com',
      'Client_Email': 'dave@live.co.uk',
      'Client_Mobile': '1231231231231',
      'Client_Pickup_Address': 'Glasgow, United Kingdom',
      'Client_Pickup_Postcode': 'G',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '55.864239',
      'Client_lng': '-4.251806',
      'Client_Pickup_Time': '2015-02-17 11:40:00'
    }, {
      'Client_id': '19',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'Hannah@Fictional.com',
      'Client_Mobile': '07905824888',
      'Client_Pickup_Address': 'Leeds, United Kingdom',
      'Client_Pickup_Postcode': 'L',
      'Client_Dropoff_Address': 'Durham, United Kingdom',
      'Client_Dropoff_Postcode': 'DH1',
      'Client_lat': '53.800755',
      'Client_lng': '-1.549077',
      'Client_Pickup_Time': '2015-02-19 12:00:00'
    }, {
      'Client_id': '20',
      'Client_Name': 'Hannah Millar',
      'Client_Email': 'Hannah@Fictional.com',
      'Client_Mobile': '07905824888',
      'Client_Pickup_Address': 'Isle of Man',
      'Client_Pickup_Postcode': 'I',
      'Client_Dropoff_Address': 'Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne63',
      'Client_lat': '54.236107',
      'Client_lng': '-4.548056',
      'Client_Pickup_Time': '2015-02-17 12:10:00'
    }, {
      'Client_id': '21',
      'Client_Name': 'Becky Osselton',
      'Client_Email': 'becky@testing.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'NE1',
      'Client_Dropoff_Address': 'Ashington, United Kingdom',
      'Client_Dropoff_Postcode': 'NE63',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-17 14:10:00'
    }, {
      'Client_id': '22',
      'Client_Name': 'Becky Osselton',
      'Client_Email': 'Becky@test.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Ashington, northumberland',
      'Client_Pickup_Postcode': 'NE63 8au',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'ne1',
      'Client_lat': '51.226414',
      'Client_lng': '1.366647',
      'Client_Pickup_Time': '2015-02-20 14:30:00'
    }, {
      'Client_id': '23',
      'Client_Name': 'Mark Fairlie',
      'Client_Email': 'mark@test.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Norwich, United Kingdom',
      'Client_Pickup_Postcode': 'E1',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '51.436661',
      'Client_lng': '-0.127482',
      'Client_Pickup_Time': '2015-02-20 14:40:00'
    }, {
      'Client_id': '24',
      'Client_Name': 'Lisa Dimmick',
      'Client_Email': 'Lisa@test.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Darlington, United Kingdom',
      'Client_Pickup_Postcode': 'D1',
      'Client_Dropoff_Address': 'Middlesbrough, United Kingdom',
      'Client_Dropoff_Postcode': 'M1',
      'Client_lat': '52.579567',
      'Client_lng': '-1.195667',
      'Client_Pickup_Time': '2015-03-03 13:51:00'
    }, {
      'Client_id': '25',
      'Client_Name': 'Lisa Dimmick',
      'Client_Email': 'Lisa@test.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Leeds, United Kingdom',
      'Client_Pickup_Postcode': 'L1',
      'Client_Dropoff_Address': 'Durham, United Kingdom',
      'Client_Dropoff_Postcode': 'Dh1',
      'Client_lat': '53.803047',
      'Client_lng': '-1.893996',
      'Client_Pickup_Time': '2015-02-18 14:20:00'
    }, {
      'Client_id': '26',
      'Client_Name': 'Dave davidson',
      'Client_Email': 'Davie@test.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Norwich, United Kingdom',
      'Client_Pickup_Postcode': 'W',
      'Client_Dropoff_Address': 'Pilgrim Street, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'ne',
      'Client_lat': '52.630886',
      'Client_lng': '1.297355',
      'Client_Pickup_Time': '2015-02-20 16:20:00'
    }, {
      'Client_id': '27',
      'Client_Name': 'Walter White',
      'Client_Email': 'breaking@bad.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Edinburgh, United Kingdom',
      'Client_Pickup_Postcode': 'E',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '55.953251',
      'Client_lng': '-3.188267',
      'Client_Pickup_Time': '2015-02-19 16:50:00'
    }, {
      'Client_id': '28',
      'Client_Name': 'Lewis Dimmick',
      'Client_Email': 'Lewis@Fictional.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'Ne1',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-18 10:30:00'
    }, {
      'Client_id': '29',
      'Client_Name': 'Flash Gordon',
      'Client_Email': 'Flash@space.gov.uk',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'Ne1',
      'Client_Dropoff_Address': 'Pink Lane Coffee, Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-19 10:20:00'
    }, {
      'Client_id': '30',
      'Client_Name': 'Lewis Dimmick',
      'Client_Email': 'Lewis@Example.com',
      'Client_Mobile': '07905824899',
      'Client_Pickup_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Pickup_Postcode': 'Ne1',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '54.969757',
      'Client_lng': '-1.618979',
      'Client_Pickup_Time': '2015-02-18 11:40:00'
    }, {
      'Client_id': '31',
      'Client_Name': 'Jim Sterling',
      'Client_Email': 'Jim@theEscapist.com',
      'Client_Mobile': '12312312312 ',
      'Client_Pickup_Address': 'Blyth, United Kingdom',
      'Client_Pickup_Postcode': 'NE1',
      'Client_Dropoff_Address': 'Pink Lane, Newcastle upon Tyne, United Kingdom',
      'Client_Dropoff_Postcode': 'Ne1',
      'Client_lat': '55.126957',
      'Client_lng': '-1.510277',
      'Client_Pickup_Time': '2015-02-18 11:50:00'
    }, {
      'Client_id': '32',
      'Client_Name': 'Ben Johnston',
      'Client_Email': 'Ben@testing.com',
      'Client_Mobile': '12312312312',
      'Client_Pickup_Address': 'Hull, United Kingdom',
      'Client_Pickup_Postcode': 'H',
      'Client_Dropoff_Address': 'Liverpool, United Kingdom',
      'Client_Dropoff_Postcode': 'L',
      'Client_lat': '53.745670',
      'Client_lng': '-0.336741',
      'Client_Pickup_Time': '2015-02-20 13:10:00'
    }];
    vm.user = {
      'uid': '53c33222e4b00a5af2968efa',
      'username': 'Lewis Dimmick',
      'firstName': 'Lewis',
      'lastName': 'Dimmick',
      'carDescription': 'Silver Peugeot 5008',
      'carReg': 'NH12 FYT',
      'email': 'lewis.dimmick@meridiandelta.com',
      'contactNumber': '07905824899',
      'passwordHash': null,
      'postalCode': null,
      'lastDateTime': null,
      'createDateTime': null,
      'country': 'UK',
      'completedJobs': 100,
      'licienced': true,
      'driverRating': 50,
      'smallAvatarUrl': 'http://www.emaildatabases.co.uk/Tools/Animate/images/logo.png',
      'largeAvatarUrl': 'http://www.emaildatabases.co.uk/Tools/Animate/images/logo.png'
    };
  });
